base_url = "https://moongangers.github.io"
title = "Archive of Hawaii Palz"
description = "welcome moongangers, behave or i'll punch your face"
theme = "shadharon"

# generate_feed = true
compile_sass = true
minify_html = true
build_search_index = true

taxonomies = [
    {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
toc = false 
use_cdn = false
search_bar = true

#Full path after the base URL required. So if you were to place it in "static" it would be "/favicon.ico"
favicon = "/images/tsinela.jpg"

#This header image is used for SEO. For example if you were to share an image via Messenger/Instagram/Twitter a preview picture is also presented
headerImage = "/images/tsinela.jpg"

# The icon is display besides the menu text but is not necessary. It needs to be placed under "menu_icon" in the static "folder"
menu = [
    { name = "Table of Contents", url = "/posts/toc/"},
]

